<?php

/**
 * Implements hook_form_alter();
 */
function event_registration_form_alter(&$form, &$form_state, $form_id) {

    if (isset($form_id) && $form_id == 'user_register_form') {
    $form['#submit'][] = 'event_registration_user_register_submit';


    $results = db_query("SELECT n.nid, n.title FROM {node} n INNER JOIN {field_data_field_event_type} f ON n.nid=f.entity_id WHERE n.status=1 AND f.field_event_type_value IN ('Job Fair', 'Sprint', 'Summit', 'Training') ORDER BY f.field_event_type_value DESC, n.title ASC")->fetchAll();

    foreach ($results as $result) {
      $options[$result->nid] = array(
        'event_name' => $result->title,
      );
    }

    $form['events'] = array(
      '#type' => 'fieldset',
      '#title' => t('Events interested in'),
      '#weight' => 6,
      '#collapsible' => FALSE,
      '#collapsed' => FALSE,
    );
    $form['events']['field_events'] = array (
      '#type' => 'tableselect',
      '#header' => array('event_name' => t('Event name')),
      '#options' => $options,
    );

  }
}

/**
 * Submit callback for user_register form.
 */
function event_registration_user_register_submit($form, &$form_state) {

  global $user;

  // Automatically assign users to the NYC Camp 2014 event
  $uid = $form_state['user']->uid;
  $group_type = 'node';
  $account = user_load($uid);
  $events = $form_state['values']['field_events'];
  foreach($events as $group_id) {
    if($group_id > 0) {
      og_group($group_type ,$group_id, array(
        "entity type" => "user",
        "entity" => $account,
        "membership type" => OG_MEMBERSHIP_TYPE_DEFAULT,
      ));
    }
  }
}
