<?php

/**
 * Implements hook_block_info().
 */
function nyccamp_block_info() {
  $blocks = array();
  $blocks['submit_session'] = array(
    'info' => t('Submit Session'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function nyccamp_block_view($delta) {
  $blocks = array();
  switch($delta) {
    case 'submit_session':
      $blocks['subject'] = t('Submit a Session');
      $blocks['content'] = _nyccamp_sc_block_content();
    break;
    }
  return $blocks;
}

/**
 * Content for the NYC Camp 'Submit a Session' block
 */
function _nyccamp_sc_block_content() {
  $block = t('<p><strong>Registration and session submissions are now open!</strong></p>
    <p><strong>Mon. Feb 22:</strong> Registration Opens/Call for Submissions</p>
    <p><strong>Fri. Mar. 15:</strong> Session Submissions extended!</p>
    <p><strong>Mon. Mar. 17:</strong> Session Schedule Announced</p>
    <p>');

  if (user_is_anonymous()) {
    $block .= '<div class="register-now">' . l(t('Register now to submit a session'), 'user/register') . '</div>';
  } elseif (!user_is_anonymous()) {
    $block .= '<div class="register-now">' . l(t('Submit a Session'), 'node/add/session') . '</div>';
  }
  
  $block .= '</p><p>' . l(t('View Proposed Sessions'), 'program/sessions/proposed') . '</p>';

  return $block;
}
