<?php

/**
 * Implements hook_block_info().
 */
function nyccamp_block_info() {
  $blocks = array();
  $blocks['submit_session'] = array(
    'info' => t('Submit Session'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function nyccamp_block_view($delta) {
  $blocks = array();
  switch($delta) {
    case 'submit_session':
      $blocks['subject'] = t('Submit a Session');
      $blocks['content'] = _nyccamp_ss_block_content();
    break;
    }
  return $blocks;
}

/**
 * Content for the NYC Camp 'Submit a Session' block
 */
function _nyccamp_ss_block_content() {
  $block = t('<p><strong>Registration and session submissions are now open!</strong></p>
    <p><strong>Mon. Feb 22:</strong> Registration Opens/Call for Submissions</p>
    <p><strong>Fri. Mar. 15:</strong> Session Submissions extended!</p>
    <p><strong>Mon. Mar. 17:</strong> Session Schedule Announced</p>');

  if (user_is_anonymous()) {
    $block .= '<div class="register-now">' . l(t('Register now to submit a session'), 'user/register') . '</div>';
  } else {
    $block .= '<div class="register-now">' . l(t('Submit a Session'), 'node/add/session') . '</div>';
  }

  $block .= '<br /><p>' . l(t('View Proposed Sessions'), 'program/sessions/proposed') . '</p>';

  return $block;
}

/**
 * Implements hook_rules_action_info().
 */
function nyccamp_rules_action_info() {
  $actions['nyccamp_remove_messages'] = array(
    'label' => t('Remove all the system messages'),
    'group' => t('NYC Camp custom actions'),
  );
  return $actions;
}

/**
 * Custom action to remove system messages
 */
function nyccamp_remove_messages() {
  // Retrieve all messages and clear the queue
  drupal_get_messages();
}

/**
 * Implements hook_block_view_alter().
 *
 */
function nyccamp_block_view_alter(&$data, $block) {
  switch ($block->delta) {
    case 'events_schedule_summits-block':
      $data['subject'] = l(t('Summits (Fri Apr 11)'), '2014/summits');
      break;
    case 'events_schedule_trainings-block':
      $data['subject'] = l(t('Trainings (Thu Apr 10)'), 'trainings');
      break;
  }
}
